export type InfinityIntent="search"|"code"|"create";export type CoderCapability={name:string;repo:string;upstream?:string;branch?:string;use:string;tags:string[];triggers?:string[];intents?:InfinityIntent[];artifacts?:string[];inspect?:string[]};const core=(name:string,repo:string,use:string,tags:string[],extra:Partial<CoderCapability>={}):CoderCapability=>({name,repo,use,tags,...extra});
export const CODER_CAPABILITIES:CoderCapability[]=[
core("Sandpack","www-infinity4/sandpack","modern browser code execution, React live previews and bundling",["preview","code","sandbox","react","website","component"],{upstream:"codesandbox/sandpack",branch:"main",intents:["code","create"],artifacts:["live preview","interactive website","component"],triggers:["preview","website","web app","component","interactive"],inspect:["README.md","sandpack-react","packages"]}),
core("shadcn/ui","www-infinity4/ui","modern accessible interface composition, cards, menus, dialogs, forms and polished application layouts",["ui","design","cards","menu","dialog","form","layout","website"],{upstream:"shadcn-ui/ui",branch:"main",intents:["search","code","create"],artifacts:["website UI","card","navigation","application layout"],triggers:["website","card","menu","layout","design","dashboard","form"],inspect:["README.md","apps","packages"]}),
core("React Three Fiber","www-infinity4/react-three-fiber","React renderer for modern Three.js 3D scenes, animation and interactive WebGL experiences",["3d","react","three","webgl","scene","animation","visual"],{upstream:"pmndrs/react-three-fiber",branch:"master",intents:["search","code","create"],artifacts:["3D website","3D card","interactive visual"],triggers:["3d","three js","scene","immersive","visual"],inspect:["README.md","packages","docs"]}),
core("ReactPlayer","www-infinity4/react-player","modern responsive video and streaming playback for media cards, feeds and websites",["video","player","media","stream","youtube","vimeo","hls"],{upstream:"cookpete/react-player",branch:"master",intents:["search","code","create"],artifacts:["video player","video card","media feed"],triggers:["video","player","youtube","stream","highlight","media feed"],inspect:["README.md","src","examples"]}),
core("Remotion","www-infinity4/remotion","programmable React video, motion graphics, animated storytelling and visual compositions",["video","animation","motion","story","visual","react","media"],{upstream:"remotion-dev/remotion",branch:"main",intents:["search","code","create"],artifacts:["animated story","video composition","motion card","visual story"],triggers:["animate","video","motion","story card","visual story","reel"],inspect:["README.md","packages","docs"]}),
core("Babylon.js","www-infinity4/Babylon.js","3D WebGL/WebGPU scenes, physics, audio and XR",["3d","game","webgl","webgpu","xr","scene"],{upstream:"BabylonJS/Babylon.js",branch:"master",intents:["code","create"],artifacts:["3D app","3D game"],triggers:["3d game","3d world","webgpu","virtual reality"],inspect:["README.md","packages"]}),
core("Tone.js","www-infinity4/Tone.js","music, synthesis, sequencing, effects and interactive Web Audio",["audio","music","sound","synth","sequencer"],{upstream:"Tonejs/Tone.js",branch:"dev",intents:["code","create"],artifacts:["audio app","music tool"],triggers:["music","sound","audio","synth"],inspect:["README.md","Tone","examples"]}),
core("FFmpeg.wasm","www-infinity4/ffmpeg.wasm","browser-side video/audio conversion, trimming and media processing",["video","audio","media","convert","trim"],{upstream:"ffmpegwasm/ffmpeg.wasm",branch:"main",intents:["code","create"],artifacts:["video tool","audio tool"],triggers:["video editor","convert video","trim audio"],inspect:["README.md","packages"]}),
core("Apache ECharts","www-infinity4/echarts","interactive charts, dashboards and data visualization",["chart","dashboard","graph","visualization"],{upstream:"apache/echarts",branch:"master",intents:["search","code","create"],artifacts:["chart","dashboard"],triggers:["chart","dashboard","visualize data"],inspect:["README.md","src"]}),
core("AG Grid","www-infinity4/ag-grid","high-performance editable data grids",["spreadsheet","grid","table","filter","sort"],{upstream:"ag-grid/ag-grid",branch:"latest",intents:["code","create"],artifacts:["data grid","spreadsheet app"],triggers:["table","grid","spreadsheet"],inspect:["README.md","packages"]}),
core("Univer","www-infinity4/univer","spreadsheet, document and presentation application infrastructure",["spreadsheet","document","presentation","office"],{upstream:"dream-num/univer",branch:"dev",intents:["code","create"],artifacts:["spreadsheet","document","presentation"],triggers:["spreadsheet","workbook","presentation"],inspect:["README.md","packages"]}),
core("Excalidraw","www-infinity4/excalidraw","editable diagrams, sketches and visual documents",["drawing","diagram","whiteboard","visual"],{upstream:"excalidraw/excalidraw",branch:"master",intents:["search","code","create"],artifacts:["diagram","whiteboard"],triggers:["diagram","sketch","whiteboard"],inspect:["README.md","packages"]}),
core("tldraw","www-infinity4/tldraw","infinite canvas and visual workspace",["canvas","whiteboard","diagram","workspace"],{upstream:"tldraw/tldraw",branch:"main",intents:["code","create"],artifacts:["infinite canvas"],triggers:["canvas","visual workspace"],inspect:["README.md","packages"]}),
core("Tiptap","www-infinity4/tiptap","rich text editing and programmable content composition",["document","editor","rich text","content","blog"],{upstream:"ueberdosis/tiptap",branch:"main",intents:["code","create"],artifacts:["editor","blog editor"],triggers:["editor","blog","rich text"],inspect:["README.md","packages"]}),
core("Rete","www-infinity4/rete","node-based visual programming and dataflow composition",["node editor","workflow","dataflow","agent"],{upstream:"retejs/rete",branch:"main",intents:["code","create"],artifacts:["node editor","workflow"],triggers:["workflow","node editor"],inspect:["README.md","src"]})];
function score(h:string,v:string[]|undefined,p:number){return(v||[]).reduce((s,x)=>s+(h.includes(x.toLowerCase())?p:0),0)}export function capabilitiesFor(prompt:string,intent?:InfinityIntent){const lower=prompt.toLowerCase();return CODER_CAPABILITIES.map(cap=>{let n=score(lower,cap.triggers,5)+score(lower,cap.tags,3)+score(lower,cap.artifacts,2);if(intent&&cap.intents?.includes(intent))n+=2;if(intent&&cap.intents?.length&&!cap.intents.includes(intent))n-=3;return{...cap,score:n}}).filter(c=>c.score>0).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,8)}export function capabilityAccessPlan(prompt:string,intent:InfinityIntent="code"){return capabilitiesFor(prompt,intent).map(cap=>{const branch=cap.branch||"main",github=`https://github.com/${cap.repo}`,rawRoot=`https://raw.githubusercontent.com/${cap.repo}/${branch}`;return{name:cap.name,use:cap.use,repo:cap.repo,upstream:cap.upstream,branch,github,rawRoot,inspect:cap.inspect||["README.md","package.json"],artifacts:cap.artifacts||[],score:cap.score}})}
