/** Intelligent, license-aware image search for Infinity Spark / Studio. */
export type LicenseGrade="A"|"B"|"C"|"D"|"E";
export type SearchImage={url:string;thumbUrl:string;alt:string;width?:number;height?:number;source:"wikimedia"|"openverse";sourceUrl:string;license:string;licenseUrl?:string;grade:LicenseGrade;creator?:string;relevance?:number};
function gradeLicense(license:string):{grade:LicenseGrade;clean:string}{const raw=license.toLowerCase().replace(/[\s\-]+/g," ");if(/public domain|cc0|no known copyright|no restrictions/i.test(raw))return{grade:"A",clean:"Public domain / CC0"};if(/cc by(?!-sa|-nc|-nd)/i.test(raw)||/attribution(?!.*share.alike)/i.test(raw))return{grade:"B",clean:"CC BY — attribution required"};if(/cc by.sa|share.alike/i.test(raw))return{grade:"C",clean:"CC BY-SA — share alike"};if(/cc by.nc|noncommercial|cc by.nd|no.deriv/i.test(raw))return{grade:"D",clean:license};if(/cc/i.test(raw))return{grade:"D",clean:license};return{grade:"E",clean:license||"Unknown license"}}
function stripHtml(v:string){return v.replace(/<[^>]*>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#039;/g,"'").replace(/\s+/g," ").trim()}
function terms(topic:string){return [...new Set(topic.toLowerCase().replace(/[^a-z0-9\s-]/g," ").split(/\s+/).filter(w=>w.length>2&&!new Set(["the","and","for","with","from","into","about","understanding","research"]).has(w)))]}
function relevance(alt:string,topic:string){const words=terms(topic),text=alt.toLowerCase();if(!words.length)return 0;const hit=words.filter(w=>text.includes(w)).length;const exact=text.includes(topic.toLowerCase().trim())?3:0;return hit/words.length+exact}
async function searchWikimedia(topic:string):Promise<SearchImage[]>{try{const endpoint=new URL("https://commons.wikimedia.org/w/api.php");endpoint.search=new URLSearchParams({action:"query",generator:"search",gsrsearch:topic,gsrnamespace:"6",gsrlimit:"20",prop:"imageinfo",iiprop:"url|extmetadata|size",iiurlwidth:"1400",format:"json",origin:"*"}).toString();const response=await fetch(endpoint,{signal:AbortSignal.timeout(8000)});if(!response.ok)return[];const json=await response.json() as {query?:{pages?:Record<string,{title?:string;imageinfo?:{url?:string;thumburl?:string;descriptionurl?:string;width?:number;height?:number;extmetadata?:Record<string,{value?:string}>}[]}>}};return Object.values(json.query?.pages||{}).flatMap(page=>{const info=page.imageinfo?.[0];if(!info?.url)return[];const meta=info.extmetadata||{},licenseName=stripHtml(meta.LicenseShortName?.value||meta.License?.value||""),creator=stripHtml(meta.Artist?.value||meta.Credit?.value||"").slice(0,100),g=gradeLicense(licenseName),alt=stripHtml(meta.ObjectName?.value||page.title?.replace(/^File:/,"")||topic),rel=relevance(alt,topic);if(g.grade==="E"||rel<=0)return[];return[{url:info.thumburl||info.url,thumbUrl:info.thumburl||info.url,alt,width:info.width,height:info.height,source:"wikimedia" as const,sourceUrl:info.descriptionurl||info.url,license:g.clean,licenseUrl:meta.LicenseUrl?.value,grade:g.grade,creator:creator||undefined,relevance:rel}]} )}catch{return[]}}
async function searchOpenverse(topic:string):Promise<SearchImage[]>{try{const endpoint=new URL("https://api.openverse.org/v1/images/");endpoint.search=new URLSearchParams({q:topic,page_size:"20",license:"pdm,by,by-sa,cc0"}).toString();const response=await fetch(endpoint,{signal:AbortSignal.timeout(8000)});if(!response.ok)return[];const json=await response.json() as {results?:{url?:string;thumbnail?:string;title?:string;foreign_landing_url?:string;license?:string;license_version?:string;license_url?:string;creator?:string;width?:number;height?:number}[]};return(json.results||[]).flatMap(r=>{if(!r.url)return[];const g=gradeLicense([r.license,r.license_version].filter(Boolean).join(" ").toUpperCase()),alt=r.title||topic,rel=relevance(alt,topic);if(g.grade==="E"||rel<=0)return[];return[{url:r.thumbnail||r.url,thumbUrl:r.thumbnail||r.url,alt,width:r.width,height:r.height,source:"openverse" as const,sourceUrl:r.foreign_landing_url||r.url,license:g.clean,licenseUrl:r.license_url,grade:g.grade,creator:r.creator,relevance:rel}]})}catch{return[]}}
function scoreImage(img:SearchImage){const license={A:30,B:22,C:16,D:6,E:0}[img.grade],resolution=img.width&&img.height?Math.min((img.width*img.height)/1_000_000,12):0,landscape=img.width&&img.height&&img.width>=img.height?5:0;return(img.relevance||0)*100+license+resolution+landscape}
export async function searchImages(topic:string):Promise<SearchImage[]>{const [wikimedia,openverse]=await Promise.all([searchWikimedia(topic),searchOpenverse(topic)]),seen=new Set<string>();return[...wikimedia,...openverse].filter(img=>{const key=img.sourceUrl||img.url;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>scoreImage(b)-scoreImage(a)).slice(0,12)}
export function gradeLabel(grade:LicenseGrade){return{A:"Public domain / CC0",B:"CC BY",C:"CC BY-SA",D:"Check terms",E:"Avoid reuse"}[grade]}
