"use client";

const TOKENS="infinityPhi:searchTokens:v1";
const ACTIVE="infinityPhi:activeSearchToken:v1";

export type PhiSearchToken={id:string;label:string;query:string;createdAt:string;updatedAt:string;items:any[]};
const clean=(value:unknown,max=1800)=>String(value||"").replace(/\s+/g," ").trim().slice(0,max);
const itemKey=(item:any)=>{const media=String(item?.mediaKind||"").toLowerCase(),file=Array.isArray(item?.files)?item.files[0]:null;if(media==="audio"||media==="video")return`${media}:${clean(file?.url||item?.mediaUrl||item?.storyKey||item?.id)}`;if(item?.selectedFromImageSearch||item?.kind==="image-seed")return`image:${clean(item?.image||item?.imageUrl||item?.storyKey||item?.id)}`;return`card:${clean(item?.storyKey||item?.url||item?.id)}`};
function read():PhiSearchToken[]{try{const value=JSON.parse(localStorage.getItem(TOKENS)||"[]");return Array.isArray(value)?value:[]}catch{return[]}}
function write(tokens:PhiSearchToken[]){try{localStorage.setItem(TOKENS,JSON.stringify(tokens.slice(0,24)))}catch{}}
function label(index:number){let n=index+1,out="";while(n>0){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26)}return`Token ${out}`}
export function beginPhiSearchToken(query:string){const tokens=read(),now=new Date().toISOString(),token:PhiSearchToken={id:`phi-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,label:label(tokens.length),query:clean(query,500),createdAt:now,updatedAt:now,items:[]};write([token,...tokens]);try{sessionStorage.setItem(ACTIVE,JSON.stringify({id:token.id,query:token.query}))}catch{}return token}
export function resolvePhiSearchToken(query:string,requestedId=""){const tokens=read(),key=clean(query,500).toLowerCase();let token=tokens.find(value=>value.id===requestedId&&clean(value.query,500).toLowerCase()===key);if(!token&&!requestedId){try{const active=JSON.parse(sessionStorage.getItem(ACTIVE)||"null");if(clean(active?.query,500).toLowerCase()===key)token=tokens.find(value=>value.id===active.id)}catch{}}if(!token)token=beginPhiSearchToken(query);try{sessionStorage.setItem(ACTIVE,JSON.stringify({id:token.id,query:token.query}))}catch{}return token}
export function appendPhiTokenItems(tokenId:string,query:string,items:any[]){if(!items.length)return resolvePhiSearchToken(query,tokenId);let tokens=read(),token=tokens.find(value=>value.id===tokenId);if(!token){token=resolvePhiSearchToken(query,tokenId);tokens=read()}const expanded=items.flatMap(item=>{const kind=String(item?.mediaKind||"").toLowerCase(),files=Array.isArray(item?.files)?item.files:[];if((kind!=="audio"&&kind!=="video")||files.length<=1)return[item];return files.map((file:any,index:number)=>({...item,id:`${clean(item?.id,300)}-file-${index}`,storyKey:`${clean(item?.storyKey||item?.url||item?.id,1200)}#file=${encodeURIComponent(clean(file?.name||file?.url,500))}`,files:[file]}))}),seen=new Set<string>(),merged=[...expanded,...(token.items||[])].filter(item=>{const key=itemKey(item);if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,160),next={...token,query:clean(query,500),updatedAt:new Date().toISOString(),items:merged};write([next,...tokens.filter(value=>value.id!==next.id)]);return next}
export function phiTokenItems(tokenId:string){return read().find(value=>value.id===tokenId)?.items||[]}
