export type PhiRetrievalRuntime = "server" | "service" | "library";

export type PhiRetrievalBackend = {id:string;repo:string;role:string;runtime:PhiRetrievalRuntime;endpointKey?:string;requiresCredentials?:boolean};
export const PHI_RETRIEVAL_BACKENDS: PhiRetrievalBackend[] = [
  {id:"meilisearch",repo:"www-infinity4/meilisearch",role:"fast lexical and hybrid index",runtime:"server",endpointKey:"meilisearch"},{id:"typesense",repo:"www-infinity4/typesense",role:"typo-tolerant instant search and field ranking",runtime:"server",endpointKey:"typesense"},{id:"qdrant",repo:"www-infinity4/qdrant",role:"vector memory and semantic retrieval",runtime:"server",endpointKey:"qdrant"},{id:"vespa",repo:"www-infinity4/vespa",role:"multi-stage retrieval and ranking",runtime:"server",endpointKey:"vespa"},{id:"opensearch",repo:"www-infinity4/OpenSearch",role:"durable BM25 and vector search",runtime:"server",endpointKey:"opensearch"},{id:"llama-index",repo:"www-infinity4/llama_index",role:"document ingestion and retrieval orchestration",runtime:"library"},{id:"flag-embedding",repo:"www-infinity4/FlagEmbedding",role:"embeddings and reranking",runtime:"library"},{id:"sentence-transformers",repo:"www-infinity4/sentence-transformers",role:"semantic embeddings and similarity",runtime:"library"},{id:"colbert",repo:"www-infinity4/ColBERT",role:"late-interaction passage retrieval",runtime:"library"},{id:"faiss",repo:"www-infinity4/faiss",role:"local vector index and nearest-neighbor retrieval",runtime:"library"},{id:"unstructured",repo:"www-infinity4/unstructured",role:"article/document extraction and chunking",runtime:"service",endpointKey:"unstructured"},{id:"crawl4ai",repo:"www-infinity4/crawl4ai",role:"web crawling and article extraction",runtime:"service",endpointKey:"crawl4ai"},{id:"searxng",repo:"www-infinity4/searxng",role:"broad metasearch and image discovery",runtime:"server",endpointKey:"searxng"},{id:"google-api-nodejs-client",repo:"www-infinity4/google-api-nodejs-client",role:"official Google API access",runtime:"library",requiresCredentials:true},{id:"js-genai",repo:"www-infinity4/js-genai",role:"Gemini/Vertex synthesis and structured reasoning",runtime:"library",requiresCredentials:true},
];
export const PHI_RETRIEVAL_BACKEND_COUNT=PHI_RETRIEVAL_BACKENDS.length;
export const PHI_SHARED_SEARCH_CONFIG_KEY="controlPhi:searchConfig:v1";
export type PhiRetrievalEndpointMap=Partial<Record<string,string>>;
export const PHI_RETRIEVAL_ENDPOINTS:PhiRetrievalEndpointMap={searxng:process.env.NEXT_PUBLIC_PHI_SEARXNG_URL?.trim()||"https://orange-brook-a2ac.marvaseater.workers.dev"};
export function runtimeRetrievalEndpoints():PhiRetrievalEndpointMap{const endpoints={...PHI_RETRIEVAL_ENDPOINTS};if(typeof window==="undefined")return endpoints;try{const raw=localStorage.getItem(PHI_SHARED_SEARCH_CONFIG_KEY);if(!raw)return endpoints;const config=JSON.parse(raw),shared=String(config?.endpoints?.searxng||config?.searxng||"").trim();if(shared)endpoints.searxng=shared}catch{}return endpoints}
export function configuredRetrievalBackends(endpoints:PhiRetrievalEndpointMap){return PHI_RETRIEVAL_BACKENDS.filter(b=>!b.endpointKey||Boolean(endpoints[b.endpointKey]))}
export type PhiRetrievedSource={title:string;url:string;excerpt:string;provider:string};
export type PhiRetrievedImage={id:string;image:string;original:string;title:string;sourceUrl:string;provider:string;description:string;resolution?:string;score?:number};
function endpointUrl(endpoint:string,params:Record<string,string>){const base=endpoint.trim().replace(/\/$/,"");return `${base}/search?${new URLSearchParams(params).toString()}`}
export async function searchSearxng(endpoint:string,query:string,limit=12):Promise<PhiRetrievedSource[]>{if(!endpoint.trim()||!query.trim())return[];const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4200);try{const response=await fetch(endpointUrl(endpoint,{q:query.trim(),format:"json"}),{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error(`SearXNG search failed (${response.status})`);const payload=await response.json();return(Array.isArray(payload?.results)?payload.results:[]).slice(0,limit).flatMap((r:any)=>{const title=String(r?.title||"").trim(),url=String(r?.url||"").trim(),excerpt=String(r?.content||r?.snippet||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return title&&url&&excerpt?[{title,url,excerpt,provider:"SearXNG"}]:[]})}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return[];throw e}finally{clearTimeout(timer)}}
export async function searchSearxngImages(endpoint:string,query:string,page=1,limit=80):Promise<PhiRetrievedImage[]>{if(!endpoint.trim()||!query.trim())return[];const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6500);try{const response=await fetch(endpointUrl(endpoint,{q:query.trim(),categories:"images",format:"json",pageno:String(Math.max(1,page)),safesearch:"1"}),{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error(`SearXNG image search failed (${response.status})`);const payload=await response.json(),seen=new Set<string>();return(Array.isArray(payload?.results)?payload.results:[]).flatMap((r:any,i:number)=>{const image=String(r?.img_src||r?.image||r?.thumbnail_src||r?.thumbnail||"").trim(),sourceUrl=String(r?.url||r?.source_url||"").trim(),title=String(r?.title||r?.content||query).replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim(),description=String(r?.content||r?.metadata||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim(),provider=String(r?.engine||r?.source||"SearXNG").trim();if(!image||seen.has(image))return[];seen.add(image);return[{id:`searx-${page}-${i}-${encodeURIComponent(image).slice(-48)}`,image:String(r?.thumbnail_src||r?.thumbnail||image),original:image,title,sourceUrl,provider,description,resolution:String(r?.resolution||""),score:Number(r?.score)||0}] }).slice(0,limit)}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return[];return[]}finally{clearTimeout(timer)}}
