export type PhiCodeWatchPhase="route"|"read-skill"|"plan"|"execute"|"verify"|"result"|"error";
export type PhiCodeWatchEvent={id:string;runId:string;at:number;phase:PhiCodeWatchPhase;status:"start"|"success"|"warning"|"error";tool?:string;repo?:string;action:string;reason?:string;evidence?:string;durationMs?:number};
export type PhiCodePlaybook={id:string;pattern:string;tools:string[];repos:string[];steps:string[];successes:number;updatedAt:number};
const TRACE_KEY="infinity_phi_code_watcher_v1",PLAYBOOK_KEY="infinity_phi_code_playbook_v1",MAX_EVENTS=80,MAX_PLAYBOOKS=20;
const clean=(value:unknown,max=900)=>String(value||"").replace(/\s+/g," ").trim().slice(0,max);
function readJson<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{const raw=localStorage.getItem(key);if(!raw)return fallback;if(raw.length>180000){localStorage.removeItem(key);return fallback}const parsed=JSON.parse(raw);return(parsed??fallback)as T}catch{return fallback}}
function writeJson(key:string,value:unknown){if(typeof window==="undefined")return;try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
export function newPhiCodeRunId(){return`phi-code-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
export function recordPhiCodeMove(event:Omit<PhiCodeWatchEvent,"id"|"at">){const full:PhiCodeWatchEvent={...event,id:`move-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,at:Date.now(),action:clean(event.action,500),reason:clean(event.reason,350),evidence:clean(event.evidence,500)};if(typeof window!=="undefined"){queueMicrotask(()=>{const events=readJson<PhiCodeWatchEvent[]>(TRACE_KEY,[]).slice(-MAX_EVENTS+1);writeJson(TRACE_KEY,[...events,full]);window.dispatchEvent(new CustomEvent("infinityphi:code-watch",{detail:full}))})}return full}
export function readPhiCodeMoves(limit=40){return readJson<PhiCodeWatchEvent[]>(TRACE_KEY,[]).slice(-Math.max(1,Math.min(limit,MAX_EVENTS)))}
export function readPhiCodePlaybooks(limit=8){return readJson<PhiCodePlaybook[]>(PLAYBOOK_KEY,[]).sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,Math.max(1,limit))}
function promptPattern(prompt:string){return clean(prompt,220).toLowerCase().replace(/https?:\/\/\S+/g,"url").replace(/\b\d+(?:\.\d+)?\b/g,"#").replace(/[^a-z0-9# +.-]+/g," ").replace(/\s+/g," ").trim()}
export function learnPhiCodePlaybook(runId:string,prompt:string){const events=readPhiCodeMoves(MAX_EVENTS).filter(e=>e.runId===runId&&e.status!=="error");if(!events.some(e=>e.phase==="result"&&e.status==="success"))return null;const tools=[...new Set(events.map(e=>clean(e.tool,100)).filter(Boolean))],repos=[...new Set(events.map(e=>clean(e.repo,180)).filter(Boolean))],steps=events.filter(e=>["route","read-skill","plan","execute","verify","result"].includes(e.phase)).map(e=>`${e.phase}: ${clean(e.action,220)}${e.tool?` [${clean(e.tool,80)}]`:""}`).filter((s,i,a)=>a.indexOf(s)===i).slice(0,12),pattern=promptPattern(prompt);if(!pattern)return null;const existing=readJson<PhiCodePlaybook[]>(PLAYBOOK_KEY,[]),prior=existing.find(i=>i.pattern===pattern),playbook:PhiCodePlaybook={id:prior?.id||`playbook-${Date.now().toString(36)}`,pattern,tools,repos,steps,successes:(prior?.successes||0)+1,updatedAt:Date.now()};writeJson(PLAYBOOK_KEY,[playbook,...existing.filter(i=>i.pattern!==pattern)].slice(0,MAX_PLAYBOOKS));return playbook}
export function phiCodeWatcherContext(prompt:string){const pattern=promptPattern(prompt),words=new Set(pattern.split(" ").filter(w=>w.length>2)),playbooks=readPhiCodePlaybooks(8).map(item=>({...item,match:item.pattern.split(" ").filter(w=>words.has(w)).length})).filter(i=>i.match>0).sort((a,b)=>b.match-a.match||b.successes-a.successes).slice(0,3).map(({pattern:learnedPattern,tools,repos,steps,successes})=>({learnedPattern,tools,repos,steps,successes}));return{playbooks,recent:[]}}
