export type PhiHistoryRecord={query?:string;title?:string;stage?:string;paper?:{title?:string;overview?:string}};

const ELEMENTS=new Map<string,string>([
["hydrogen","Hydrogen (chemical element)"],["helium","Helium (chemical element)"],["lithium","Lithium (chemical element)"],["beryllium","Beryllium (chemical element)"],["boron","Boron (chemical element)"],["carbon","Carbon (chemical element)"],["nitrogen","Nitrogen (chemical element)"],["oxygen","Oxygen (chemical element)"],["fluorine","Fluorine (chemical element)"],["neon","Neon (chemical element)"],["sodium","Sodium (chemical element)"],["magnesium","Magnesium (chemical element)"],["aluminum","Aluminium (chemical element)"],["silicon","Silicon (chemical element)"],["phosphorus","Phosphorus (chemical element)"],["sulfur","Sulfur (chemical element)"],["chlorine","Chlorine (chemical element)"],["argon","Argon (chemical element)"],["potassium","Potassium (chemical element)"],["calcium","Calcium (chemical element)"],["iron","Iron (chemical element)"],["cobalt","Cobalt (chemical element)"],["nickel","Nickel (chemical element)"],["copper","Copper (chemical element)"],["zinc","Zinc (chemical element)"],["gallium","Gallium (chemical element)"],["germanium","Germanium (chemical element)"],["arsenic","Arsenic (chemical element)"],["selenium","Selenium (chemical element)"],["bromine","Bromine (chemical element)"],["krypton","Krypton (chemical element)"],["silver","Silver (chemical element)"],["tin","Tin (chemical element)"],["antimony","Antimony (chemical element)"],["iodine","Iodine (chemical element)"],["xenon","Xenon (chemical element)"],["cesium","Caesium (chemical element)"],["barium","Barium (chemical element)"],["tungsten","Tungsten (chemical element)"],["rhenium","Rhenium (chemical element)"],["platinum","Platinum (chemical element)"],["gold","Gold (chemical element)"],["mercury","Mercury (element)"],["lead","Lead (chemical element)"],["bismuth","Bismuth (chemical element)"],["radon","Radon (chemical element)"],["uranium","Uranium (chemical element)"],["neodymium","Neodymium (chemical element)"],["dysprosium","Dysprosium (chemical element)"],["yttrium","Yttrium (chemical element)"],["niobium","Niobium (chemical element)"],["vanadium","Vanadium (chemical element)"]]);
const MATERIAL_WORDS=/\b(element|elements|periodic|atom|atomic|isotope|oxide|metal|alloy|ion|ionic|electron|molecule|chemical|chemistry|material|materials)\b/i;
const PERSON_WORDS=/\b(singer|song|album|band|queen|music|musician|vocalist|concert|biography)\b/i;
function elementHits(history:PhiHistoryRecord[]){return history.slice(0,30).reduce((n,r)=>{const q=String(r.query||"").trim().toLowerCase();const text=`${r.query||""} ${r.title||""} ${r.paper?.title||""}`;return n+(ELEMENTS.has(q)||MATERIAL_WORDS.test(text)?1:0)},0)}
function personHits(history:PhiHistoryRecord[]){return history.slice(0,30).reduce((n,r)=>n+(PERSON_WORDS.test(`${r.query||""} ${r.title||""}`)?1:0),0)}
export function contextualResearchTopic(input:string,history:PhiHistoryRecord[]){const raw=input.replace(/\s+/g," ").trim(),key=raw.toLowerCase();if(!raw)return raw;const explicitMaterial=MATERIAL_WORDS.test(raw),explicitPerson=PERSON_WORDS.test(raw);if(explicitPerson)return raw;if(ELEMENTS.has(key)&&(explicitMaterial||elementHits(history)>=2&&elementHits(history)>personHits(history)))return ELEMENTS.get(key)!;return raw}
export function contextualDisplayTopic(input:string){return input.replace(/\s*\((chemical )?element\)\s*$/i,"").trim()}
