import type { SemanticResearch } from "./research-semantics";

export type VisualBeat={id:string;text:string;visualPrompt:string;mode:"hero"|"image"|"gif"|"diagram"|"cutout"|"chart";motion:"static"|"loop"|"transition"|"float";layout:"full"|"left"|"right"|"overlay"};
export type VisualStoryboard={title:string;beats:VisualBeat[]};
const clean=(x:unknown)=>String(x||"").replace(/\s+/g," ").trim();
const sentences=(x:string)=>clean(x).split(/(?<=[.!?])\s+(?=[A-Z0-9])/).map(clean).filter(Boolean);
function modeFor(text:string,i:number):VisualBeat["mode"]{const t=text.toLowerCase();if(/architecture|schematic|wire|circuit|structure|vector|flow|system|network/.test(t))return"diagram";if(/compare|versus|difference|rate|percent|increase|decrease|data|measurement/.test(t))return"chart";if(/move|turn|reshape|optimi|assemble|process|react|spin|flow|transform/.test(t))return"gif";if(/object|component|tool|device|box|material|sample/.test(t))return"cutout";return i===0?"hero":"image"}
function promptFor(title:string,text:string,mode:VisualBeat["mode"]){const base=`${title}. ${text}`;if(mode==="diagram")return`Precise clean technical visualization of ${base}. Legible structure, no decorative text, publication quality.`;if(mode==="chart")return`Clear data visualization illustrating ${base}. Minimal labels, publication quality.`;if(mode==="gif")return`Short seamless visual sequence illustrating ${base}. Clear beginning, action and resolved final frame.`;if(mode==="cutout")return`Isolated detailed subject illustrating ${base}, transparent or clean neutral background, suitable for floating over editorial text.`;return`Editorial illustration accurately depicting ${base}, visually informative, publication quality.`}
export function storyboardResearch(r:SemanticResearch,titleFallback="Infinity research"):VisualStoryboard{const title=clean(r.title)||titleFallback,raw=[r.dek||"",r.overview||"",...(r.keyTakeaways||[]),...(r.findings||[]),...(r.engineering||[]),...(r.context||[]),...(r.opportunities||[]),...(r.cautions||[]),...(r.next||[])],passages=raw.flatMap(sentences).filter((v,i,a)=>v.length>25&&a.findIndex(x=>x.slice(0,120).toLowerCase()===v.slice(0,120).toLowerCase())===i);return{title,beats:passages.map((text,i)=>{const mode=modeFor(text,i);return{id:`beat-${i+1}`,text,mode,visualPrompt:promptFor(title,text,mode),motion:mode==="gif"?"loop":mode==="cutout"?"float":i%4===3?"transition":"static",layout:i===0?"full":i%3===0?"overlay":i%2?"right":"left"}})}}
