"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {BookOpen,Check,ChevronRight,Download,ExternalLink,Globe2,History,Layers3,LoaderCircle,Menu,Search,Share2,Sparkles,Wallet,Wrench,X} from "lucide-react";

type Source={title:string;url:string;excerpt:string;kind:string};
type Paper={title:string;dek:string;overview:string;context:string[];findings:string[];opportunities:string[];cautions:string[];next:string[];sources:Source[]};
type Stage="query"|"research"|"webpage"|"tools"|"design"|"advertising"|"assets";
type Token={id:string;query:string;title:string;stage:Stage;createdAt:string;units:number;estimate:number;paper?:Paper};
type WalletRecord={walletId:string;displayName:string};
type WalletApi={createWallet(input:{displayName:string}):WalletRecord;snapshot():{currentWalletId:string|null;wallets:Record<string,WalletRecord>}};
declare global{interface Window{__infinitySparkHandoff?:string;InfinityUnifiedWallet?:{UnifiedInfinityWallet:new()=>WalletApi}}}

const KEY="c13b0_infinity_token_ledger_v3",HANDOFF="c13b0_infinity_spark_handoff_v3";
const stages:{key:Stage;label:string;note:string;estimate:number;icon:typeof Search}[]=[
 {key:"query",label:"Search",note:"Original question",estimate:1,icon:Search},
 {key:"research",label:"Response",note:"Evidence-built paper",estimate:180,icon:BookOpen},
 {key:"webpage",label:"Webpage",note:"Published subject home",estimate:750,icon:Globe2},
 {key:"tools",label:"Tools",note:"Useful working features",estimate:1600,icon:Wrench},
 {key:"design",label:"Design",note:"Unique visual system",estimate:2400,icon:Layers3},
 {key:"advertising",label:"Advertising",note:"Audience and offers",estimate:4200,icon:Share2},
 {key:"assets",label:"Assets",note:"Documented real-world links",estimate:8000,icon:Sparkles},
];
function read(){try{return JSON.parse(localStorage.getItem(KEY)||"[]") as Token[]}catch{return[]}}
function save(x:Token[]){try{localStorage.setItem(KEY,JSON.stringify(x.slice(0,100)))}catch{}}
function plain(x:unknown){return String(x||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
function words(x:string){return new Set(x.toLowerCase().match(/[a-z0-9]{3,}/g)||[])}
function sentences(x:string){return plain(x).split(/(?<=[.!?])\s+/).filter(s=>s.length>42&&s.length<440)}
function unique(x:string[]){return x.filter((v,i,a)=>a.findIndex(y=>y.slice(0,90).toLowerCase()===v.slice(0,90).toLowerCase())===i)}
function makePaper(topic:string,sources:Source[]):Paper{
 const wanted=words(topic),ranked=sources.flatMap((source,si)=>sentences(source.excerpt).map((sentence,i)=>({sentence,source,score:[...words(sentence)].filter(x=>wanted.has(x)).length*14+Math.max(0,10-si)+(i?0:4)}))).sort((a,b)=>b.score-a.score);
 const evidence=unique(ranked.map(x=>x.sentence));
 return{title:topic,dek:`A sourced starting point for understanding ${topic}, what the evidence supports, and what can be built next.`,overview:evidence.slice(0,3).join(" ")||`Available sources identify ${topic} as a subject worth further verification, but do not support a dependable short conclusion yet.`,context:unique(evidence.slice(1,6)),findings:ranked.slice(0,8).map(x=>`${x.sentence} — ${x.source.title}`),opportunities:[`Build a focused reference page answering common questions about ${topic}.`,"Turn repeated calculations, comparisons, or decisions into a useful interactive tool.","Track new publications and practical applications so the work improves over time."],cautions:["Source quality varies; summaries are not substitutes for the underlying work.","Recent, private, local, or paywalled evidence may be absent.","Technical, medical, legal, and financial claims require qualified review before real-world use."],next:[`What evidence would disprove the strongest claim about ${topic}?`,"Who already solves this well, and where are the gaps?","What is the smallest useful tool that can be tested with real users?"],sources};
}

export default function SparkSearch(){
 const[query,setQuery]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[paper,setPaper]=useState<Paper|null>(null);
 const[wallet,setWallet]=useState<WalletRecord|null>(null),[ledger,setLedger]=useState<Token[]>([]),[menu,setMenu]=useState(false),[tab,setTab]=useState<"wallet"|"history"|"ledger">("wallet"),[filter,setFilter]=useState(""),[selected,setSelected]=useState<Token|null>(null),[expanded,setExpanded]=useState(false);
 useEffect(()=>{setLedger(read());try{if(window.InfinityUnifiedWallet){const api=new window.InfinityUnifiedWallet.UnifiedInfinityWallet(),s=api.snapshot();if(s.currentWalletId)setWallet(s.wallets[s.currentWalletId]||null)}}catch{}},[]);
 const visible=useMemo(()=>ledger.filter(x=>`${x.query} ${x.title} ${x.stage}`.toLowerCase().includes(filter.toLowerCase())),[ledger,filter]);
 function openWallet(){try{if(!window.InfinityUnifiedWallet)return;const api=new window.InfinityUnifiedWallet.UnifiedInfinityWallet(),s=api.snapshot(),w=s.currentWalletId?s.wallets[s.currentWalletId]:null;setWallet(w||api.createWallet({displayName:"Infinity Wallet"}))}catch{}}
 function add(stage:Stage,title:string,p:Paper|null=paper){const info=stages.find(x=>x.key===stage)!;const token:Token={id:crypto.randomUUID(),query:query.trim(),title,stage,createdAt:new Date().toISOString(),units:1,estimate:info.estimate,...(p?{paper:p}:{})};const next=[token,...ledger];setLedger(next);save(next);setSelected(token);return token}
 async function research(e:FormEvent){e.preventDefault();const topic=query.trim();if(!topic||loading)return;setLoading(true);setError("");setPaper(null);setExpanded(false);add("query",topic,null);try{
  const r=await Promise.allSettled([
   fetch(`https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(topic)}&gsrlimit=10&prop=extracts%7Cinfo&explaintext=1&exsentences=10&inprop=url&format=json&origin=*`).then(x=>x.json()),
   fetch(`https://api.duckduckgo.com/?q=${encodeURIComponent(topic)}&format=json&no_html=1&skip_disambig=1`).then(x=>x.json()),
   fetch(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(topic)}&rows=8&select=DOI,title,abstract,URL`).then(x=>x.json())]);
  const wiki=r[0].status==="fulfilled"?r[0].value:null,duck=r[1].status==="fulfilled"?r[1].value:null,cross=r[2].status==="fulfilled"?r[2].value:null;
  const pages=Object.values(wiki?.query?.pages||{}) as {title?:string;extract?:string;fullurl?:string;index?:number}[];pages.sort((a,b)=>Number(a.index||99)-Number(b.index||99));
  const sources:Source[]=pages.filter(p=>p.extract&&p.fullurl).map(p=>({title:plain(p.title),url:String(p.fullurl),excerpt:plain(p.extract),kind:"Reference"}));
  if(plain(duck?.AbstractText)&&duck?.AbstractURL)sources.unshift({title:plain(duck.Heading)||topic,url:String(duck.AbstractURL),excerpt:plain(duck.AbstractText),kind:"Indexed overview"});
  for(const p of(cross?.message?.items||[])as {title?:string[];abstract?:string;URL?:string}[])if(p.title?.[0]&&p.URL)sources.push({title:plain(p.title[0]),url:String(p.URL),excerpt:plain(p.abstract)||"Relevant publication record located; open it to evaluate the full work.",kind:"Publication"});
  if(!sources.length)throw new Error("No usable public sources came back. Try a more specific wording.");const next=makePaper(topic,sources);setPaper(next);add("research",`${topic} — research paper`,next);
 }catch(c){setError(c instanceof Error?c.message:"The research could not be completed.")}finally{setLoading(false)}}
 function advance(stage:Stage){if(!paper)return;const token=add(stage,`${paper.title} — ${stages.find(x=>x.key===stage)?.label}`,paper);const data=JSON.stringify({schema:"infinity/project-token/v3",walletId:wallet?.walletId||null,token,paper,chain:ledger.filter(x=>x.query===query.trim())});try{localStorage.setItem(HANDOFF,data)}catch{}window.__infinitySparkHandoff=data;if(stage==="webpage")location.href=`../business/?query=${encodeURIComponent(query.trim())}`}
 async function share(){try{if(navigator.share)await navigator.share({title:paper?.title||"Infinity",text:paper?.dek||"Build from a question with Infinity.",url:location.href});else await navigator.clipboard.writeText(location.href)}catch{}}
 function backup(){const blob=new Blob([JSON.stringify({schema:"infinity/wallet-backup/v1",exportedAt:new Date().toISOString(),wallet,tokens:ledger},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="infinity-wallet-backup.json";a.click();URL.revokeObjectURL(url)}
 const idle=!loading&&!paper&&!error;
 return <main className="min-h-screen bg-[radial-gradient(circle_at_50%_-10%,#174c78_0%,#0b2e50_42%,#061d35_100%)] text-white">
  <header className="fixed inset-x-0 top-0 z-40 flex h-16 items-center justify-between border-b border-white/10 bg-[#071f38]/85 px-4 backdrop-blur-xl sm:px-7"><div className="flex items-center gap-2"><button onClick={()=>setMenu(true)} className="grid size-11 place-items-center rounded-full hover:bg-white/10" aria-label="Open Infinity menu"><Menu/></button><div className="flex items-center gap-2 font-serif text-xl font-black text-white"><span className="grid size-8 place-items-center rounded-full border border-white/25 font-sans text-2xl font-light">φ</span>Infinity</div></div><button onClick={share} className="grid size-11 place-items-center rounded-full hover:bg-white/10" aria-label="Share"><Share2 size={20}/></button></header>
  <section className={`flex px-4 pt-16 ${idle?"min-h-screen items-center pb-28":"border-b border-white/10 py-9"}`}><form onSubmit={research} className="mx-auto w-full max-w-4xl text-center"><div className={`${idle?"text-7xl sm:text-9xl":"text-5xl"} font-serif font-black tracking-[-.06em] text-white`}><span className="mr-3 font-sans font-light">φ</span>Infinity</div><label className="mt-8 flex items-center gap-3 rounded-full border border-white/25 bg-white p-2 text-[#112b43] shadow-[0_18px_60px_rgba(0,0,0,.3)] focus-within:ring-4 focus-within:ring-white/15"><Search className="ml-4 text-[#4d6b86]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent py-3 text-lg outline-none" placeholder="Search or ask anything" aria-label="Search or ask anything"/><button disabled={loading||!query.trim()} className="grid size-12 place-items-center rounded-full bg-[#0b3154] font-serif text-2xl text-white transition hover:bg-[#174f7f] disabled:opacity-35" aria-label="Search with Pi">{loading?<LoaderCircle className="animate-spin"/>:"π"}</button></label></form></section>
  {!idle&&<section className="mx-auto max-w-6xl px-4 py-10 sm:px-7">{loading&&<div className="mx-auto max-w-3xl rounded-3xl border bg-white p-12 text-center"><LoaderCircle className="mx-auto animate-spin text-[#215f99]"/><p className="mt-4 text-lg font-bold">Reading sources and building the paper…</p><p className="mt-2 text-[#607386]">Your query is already preserved as its first token.</p></div>}{error&&<div role="alert" className="mx-auto max-w-3xl rounded-2xl border border-red-600 bg-white p-6 text-red-800"><b>Search did not complete.</b> {error}</div>}{paper&&<article className="mx-auto max-w-4xl rounded-[2rem] border border-white/15 bg-white px-6 py-8 text-[#172331] shadow-[0_30px_100px_rgba(0,0,0,.28)] sm:px-11 sm:py-12"><p className="text-sm font-bold text-[#40627e]">Your search for <span className="text-[#123f66]">“{paper.title}”</span> pulled up {paper.sources.length} relevant articles and records using those terms together.</p><h2 className="mt-5 font-serif text-4xl font-black leading-tight sm:text-6xl">{paper.title}</h2><p className="mt-5 text-xl leading-8 text-[#566b7f]">{paper.dek}</p><Section title="Overview"><p>{paper.overview}</p></Section>
   <section className="mt-10 rounded-[1.6rem] bg-[#0c3153] p-6 text-white sm:p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#9ac7e9]">Assembly package</p><h3 className="mt-2 font-serif text-3xl font-black">Model Your World!</h3><p className="mt-3 max-w-2xl text-lg leading-8 text-white/75">The best way to begin modeling your curated query is to choose the next useful form. Infinity carries the overview, sources, query history, and token record forward automatically.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{stages.slice(2).map(s=><button key={s.key} onClick={()=>advance(s.key)} className="flex items-center gap-3 rounded-xl border border-white/15 bg-white/5 p-4 text-left transition hover:-translate-y-0.5 hover:bg-white/12"><s.icon size={19} className="text-[#f0bd55]"/><span className="flex-1"><b className="block">{s.label}</b><small className="text-[#b7c8d8]">{s.note}</small></span><ChevronRight size={17}/></button>)}</div></section>
   <Section title="Refine this search"><form onSubmit={research} className="flex items-center gap-2 rounded-full border border-[#c7d2dc] p-2"><Search className="ml-3 text-[#607386]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 py-2 outline-none" placeholder="Add another term"/><button className="rounded-full bg-[#123f66] px-5 py-2 font-bold text-white">Search</button></form><p className="mt-2 text-sm text-[#607386]">A refined query creates a new overview and a new linked token.</p></Section>
   <button onClick={()=>setExpanded(x=>!x)} className="mt-10 w-full rounded-xl border border-[#9eb1c2] px-5 py-4 font-bold text-[#123f66] hover:bg-[#eef4f8]">{expanded?"Close expanded research":"Expanded research"}</button>
   {expanded&&<div><Section title="What the evidence establishes"><Numbered items={paper.findings}/></Section><Section title="Context and nuance"><Bullets items={paper.context}/></Section><Section title="Useful directions"><Bullets items={paper.opportunities}/></Section><Section title="Limits and cautions"><Bullets items={paper.cautions}/></Section><Section title="Questions worth answering next"><Bullets items={paper.next}/></Section><Section title="Sources"><div className="grid gap-2">{paper.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="flex justify-between gap-4 rounded-xl border px-4 py-3 hover:border-[#215f99]"><span><small className="block font-bold uppercase text-[#9a6317]">{s.kind}</small>{s.title}</span><ExternalLink size={16}/></a>)}</div></Section></div>}
  </article>}</section>}
  {menu&&<div className="fixed inset-0 z-50 bg-[#0c1825]/45 backdrop-blur-sm" onMouseDown={()=>setMenu(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-white shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex h-16 items-center justify-between border-b px-5"><b className="font-serif text-xl text-[#163f6b]">Infinity</b><button onClick={()=>setMenu(false)} className="grid size-10 place-items-center rounded-full hover:bg-[#edf2f7]" aria-label="Close"><X/></button></div><div className="grid grid-cols-3 border-b p-2">{([["wallet",Wallet,"Wallet"],["history",History,"History"],["ledger",Search,"Ledger"]]as const).map(([k,I,l])=><button key={k} onClick={()=>setTab(k)} className={`flex items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold ${tab===k?"bg-[#dceaf6] text-[#174d7e]":"text-[#607386]"}`}><I size={17}/>{l}</button>)}</div><div className="flex-1 overflow-y-auto p-5">
   {tab==="wallet"&&<div><p className="text-sm font-bold uppercase tracking-wider text-[#607386]">Unified wallet</p>{wallet?<div className="mt-4 rounded-2xl bg-[#172f49] p-5 text-white"><b>{wallet.displayName}</b><p className="mt-2 break-all font-mono text-xs text-[#b7c8d8]">{wallet.walletId}</p></div>:<button onClick={openWallet} className="mt-4 w-full rounded-xl bg-[#215f99] px-4 py-3 font-bold text-white">Open unified wallet</button>}<div className="mt-6 grid grid-cols-2 gap-3"><Stat label="Tokens" value={String(ledger.length)}/><Stat label="Infinity units" value={String(ledger.reduce((n,t)=>n+t.units,0))}/></div><p className="mt-5 text-sm leading-6 text-[#607386]">Every stored action remains one transferable Infinity unit. Project estimates describe attached work; they are not guaranteed sale prices.</p><button onClick={backup} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border px-4 py-3 font-bold"><Download size={18}/>Export wallet backup</button><p className="mt-3 text-xs leading-5 text-[#77899a]">Google Drive synchronization requires secure sign-in and server authorization. The export keeps recovery possible until that connection is added.</p></div>}
   {tab==="history"&&<TokenList records={ledger} empty="Your searches and builds will appear here." open={setSelected}/>}
   {tab==="ledger"&&<div><label className="flex items-center gap-2 rounded-xl border px-3"><Search size={17}/><input value={filter} onChange={e=>setFilter(e.target.value)} className="min-w-0 flex-1 py-3 outline-none" placeholder="Search tokens and websites"/></label><div className="mt-4"><TokenList records={visible} empty="No matching tokens." open={setSelected}/></div></div>}
  </div>{selected&&<div className="border-t bg-[#f4f7fa] p-5"><div className="flex justify-between gap-4"><div><small className="font-bold uppercase text-[#9a6317]">{selected.stage}</small><b className="block">{selected.title}</b><p className="mt-1 font-mono text-xs text-[#607386]">{selected.id}</p><p className="mt-2 text-xs text-[#607386]">1 Infinity unit · project work reference ${selected.estimate.toLocaleString()}</p></div><Check className="text-[#23855b]"/></div></div>}</aside></div>}
 </main>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-10 border-t pt-8"><h3 className="font-serif text-2xl font-black">{title}</h3><div className="mt-4 text-[1.05rem] leading-8 text-[#33495d]">{children}</div></section>}
function Bullets({items}:{items:string[]}){return <ul className="space-y-3">{items.map((x,i)=><li key={i} className="grid grid-cols-[18px_1fr] gap-3"><span className="mt-3 size-1.5 rounded-full bg-[#d29a2e]"/>{x}</li>)}</ul>}
function Numbered({items}:{items:string[]}){return <ol className="space-y-4">{items.map((x,i)=><li key={i} className="grid grid-cols-[34px_1fr] gap-3"><b className="font-mono text-[#9a6317]">{String(i+1).padStart(2,"0")}</b><span>{x}</span></li>)}</ol>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-[#f7f9fb] p-4"><small className="text-[#607386]">{label}</small><b className="mt-1 block text-2xl">{value}</b></div>}
function TokenList({records,empty,open}:{records:Token[];empty:string;open:(x:Token)=>void}){return records.length?<div className="space-y-2">{records.map(t=><button key={t.id} onClick={()=>open(t)} className="w-full rounded-xl border p-4 text-left hover:border-[#215f99]"><div className="flex justify-between gap-3"><span><small className="font-bold uppercase text-[#9a6317]">{t.stage}</small><b className="block">{t.title}</b><small className="text-[#77899a]">{new Date(t.createdAt).toLocaleString()}</small></span><span className="rounded-full bg-[#e4edf5] px-2 py-1 text-xs font-bold">1</span></div></button>)}</div>:<p className="py-10 text-center text-[#77899a]">{empty}</p>}
