"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { appPath } from "@/lib/base-path";
import styles from "./page.module.css";

type ImageResult={id:string;image:string;original:string;title:string;sourceUrl:string;provider:string;description:string};
const KEY="infinity_phi_image_selections_v2",OVERVIEW_KEY="infinity_phi_selected_image_overview_v1";
const clean=(v:unknown)=>String(v||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
function readSelected():ImageResult[]{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function persist(v:ImageResult[]){try{localStorage.setItem(KEY,JSON.stringify(v.slice(-250)))}catch{}}
export default function InfinityImagesPage(){
 const[query,setQuery]=useState(""),[active,setActive]=useState(""),[items,setItems]=useState<ImageResult[]>([]),[selected,setSelected]=useState<ImageResult[]>([]),[loading,setLoading]=useState(false),[offset,setOffset]=useState(0);const selectedRef=useRef<ImageResult[]>([]);
 useEffect(()=>{const saved=readSelected();selectedRef.current=saved;setSelected(saved);const initial=clean(new URLSearchParams(location.search).get("q"));setQuery(initial);setActive(initial);if(initial)void fetchImages(initial,0,true)},[]);
 const chosen=useMemo(()=>new Set(selected.map(x=>x.id)),[selected]);
 async function fetchImages(term:string,nextOffset=0,replace=true){if(!term)return;setLoading(true);try{const params=new URLSearchParams({action:"query",generator:"search",gsrsearch:term,gsrnamespace:"6",gsrlimit:"50",gsroffset:String(nextOffset),prop:"imageinfo",iiprop:"url|extmetadata",iiurlwidth:"1200",format:"json",origin:"*"});const r=await fetch(`https://commons.wikimedia.org/w/api.php?${params}`,{cache:"no-store"});if(!r.ok)throw new Error("image search failed");const j=await r.json();const next:ImageResult[]=Object.values(j.query?.pages||{}).map((raw:any)=>{const info=raw.imageinfo?.[0]||{},meta=info.extmetadata||{},original=clean(info.url),image=clean(info.thumburl)||original,title=clean(String(raw.title||"").replace(/^File:/,""))||term;return{id:String(raw.pageid||original||image),image,original,title,sourceUrl:clean(info.descriptionurl),provider:"Wikimedia Commons",description:clean(meta.ImageDescription?.value||meta.ObjectName?.value||"")}}).filter(x=>x.image);setItems(old=>replace?next:[...old,...next.filter(x=>!old.some(y=>y.id===x.id))]);setOffset(nextOffset)}catch{if(replace)setItems([])}finally{setLoading(false)}}
 function submit(e:FormEvent){e.preventDefault();const term=clean(query);if(!term)return;setActive(term);const u=new URL(location.href);u.pathname=appPath("phi/images");u.search="";u.searchParams.set("q",term);history.replaceState({},"",u.toString());void fetchImages(term,0,true)}
 function toggle(item:ImageResult){const current=selectedRef.current;const exists=current.some(x=>x.id===item.id);const next=exists?current.filter(x=>x.id!==item.id):[...current,item];selectedRef.current=next;setSelected(next);persist(next)}
 function more(){void fetchImages(active,offset+50,false)}
 function buildOverview(){const images=selectedRef.current;if(!images.length)return;const term=clean(active||query);try{localStorage.setItem(OVERVIEW_KEY,JSON.stringify({version:"infinity-images-v1",query:term,createdAt:new Date().toISOString(),images:images.map(x=>({id:x.id,image:x.image,original:x.original,title:x.title,sourceUrl:x.sourceUrl,provider:x.provider,description:x.description}))}))}catch{}const p=new URLSearchParams({q:term,run:"1",images:"selected"});location.assign(`${appPath("")}?${p.toString()}`)}
 return <main className={styles.shell}><header className={styles.top}><a href={appPath("")} className={styles.back}>← Infinity Phi</a><div className={styles.actions}><b>{selected.length} selected</b><button type="button" className={styles.overview} disabled={!selected.length} onClick={buildOverview}>AI Overview →</button></div></header><section className={styles.hero}><small>INFINITY PHI IMAGES</small><h1>{active?`Images for ${active}`:"Image Search"}</h1><p>Tap images you want to build with. AI Overview uses those exact selected images as the visual layer for its article and orange cards.</p><form onSubmit={submit} className={styles.search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search images"/><button type="submit">Search Images</button></form></section><section className={styles.grid}>{items.map(item=>{const isSelected=chosen.has(item.id);return <button type="button" key={item.id} className={`${styles.card} ${isSelected?styles.selected:""}`} onPointerUp={e=>{e.preventDefault();toggle(item)}} aria-pressed={isSelected} aria-label={`${isSelected?"Remove":"Select"} ${item.title}`}><img src={item.image} alt={item.title} loading="lazy" draggable={false} onError={e=>{if(item.original&&e.currentTarget.src!==item.original)e.currentTarget.src=item.original}}/><span><b>{item.title}</b>{item.description&&<small>{item.description.slice(0,150)}</small>}</span>{isSelected&&<i aria-hidden="true">✓</i>}</button>})}{loading&&<div className={styles.notice}>Finding images…</div>}{!loading&&active&&!items.length&&<div className={styles.notice}>No images returned. Try another wording.</div>}</section>{items.length>0&&<button type="button" className={styles.more} onClick={more} disabled={loading}>Load more images ↓</button>}</main>
}
