"use client";
import { useState } from "react";
import { appPath } from "@/lib/base-path";

export default function CodePhiPage(){
 const [min,setMin]=useState("1"),[max,setMax]=useState("100"),[count,setCount]=useState("1"),[result,setResult]=useState<number[]>([]),[prompt,setPrompt]=useState(""),[message,setMessage]=useState("Tap Generate to pick a number from 1–100.");
 function generate(){let lo=Math.ceil(Number(min)),hi=Math.floor(Number(max)),n=Math.max(1,Math.min(100,Math.floor(Number(count)||1)));if(!Number.isSafeInteger(lo)||!Number.isSafeInteger(hi)){setResult([]);setMessage("Enter whole numbers.");return}if(lo>hi)[lo,hi]=[hi,lo];const span=hi-lo+1;if(!Number.isSafeInteger(span)||span<1){setResult([]);setMessage("That number range is too large.");return}const out=Array.from({length:n},()=>lo+Math.floor(Math.random()*span));setResult(out);setMessage(`${n} number${n===1?"":"s"} generated.`)}
 const panel:React.CSSProperties={background:"#fff",border:"1px solid #dfe4ea",borderRadius:20,padding:20,boxShadow:"0 10px 28px #17202a0b"},input:React.CSSProperties={width:"100%",padding:12,border:"1px solid #cbd3dc",borderRadius:12,background:"#fff",color:"#17202a",font:"inherit"},button:React.CSSProperties={border:0,borderRadius:12,padding:"13px 15px",background:"#168a52",color:"#fff",fontWeight:900,cursor:"pointer"};
 return <main style={{minHeight:"100dvh",background:"#f7f8fa",color:"#17202a",fontFamily:"system-ui,sans-serif"}}><header style={{background:"#fff",borderBottom:"1px solid #e1e5e9"}}><div style={{width:"min(1000px,94vw)",height:64,margin:"auto",display:"flex",alignItems:"center",justifyContent:"space-between"}}><a href={appPath("phi")} style={{color:"#17202a",textDecoration:"none",fontWeight:950}}>← Code Phi</a><span style={{fontSize:12,fontWeight:900,color:"#168a52"}}>LIGHT MODE</span></div></header><section style={{width:"min(1000px,94vw)",margin:"auto",padding:"22px 0 60px"}}><div style={panel}><div style={{color:"#6f2dbd",fontSize:12,fontWeight:950,letterSpacing:".12em"}}>CODE φ</div><h1 style={{fontSize:"clamp(34px,7vw,58px)",lineHeight:1,margin:"10px 0"}}>Useful tools, without the wait.</h1><p style={{color:"#56616c",lineHeight:1.6}}>The generator is completely local and performs one short calculation per number. Nothing loads in the background.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,330px),1fr))",gap:16,marginTop:16}}><section style={panel}><div style={{color:"#6f2dbd",fontWeight:950}}>RANDOM NUMBER GENERATOR</div><h2>Pick random numbers</h2><div style={{display:"grid",gap:10}}><label>Minimum<input value={min} onChange={e=>setMin(e.target.value)} inputMode="numeric" style={input}/></label><label>Maximum<input value={max} onChange={e=>setMax(e.target.value)} inputMode="numeric" style={input}/></label><label>How many?<input value={count} onChange={e=>setCount(e.target.value)} inputMode="numeric" style={input}/></label><button type="button" onClick={generate} style={button}>Generate</button></div><div aria-live="polite" style={{marginTop:16,minHeight:84,padding:16,borderRadius:14,background:"#f3f5f7",border:"1px solid #e0e4e8",fontSize:result.length===1?42:20,fontWeight:950,wordBreak:"break-word"}}>{result.length?result.join(", "):message}</div>{result.length?<button type="button" onClick={()=>{try{navigator.clipboard?.writeText(result.join(", "))}catch{}}} style={{...button,background:"#fff",color:"#17202a",border:"1px solid #cbd3dc",marginTop:9}}>Copy</button>:null}</section><section style={panel}><div style={{color:"#6f2dbd",fontWeight:950}}>GPT BUILDER</div><h2>Build something larger</h2><p style={{color:"#64707c",lineHeight:1.5}}>This is separate from the generator. GPT only loads after you choose to open it.</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="Describe a calculator, generator, app, game, data tool…" style={{...input,resize:"vertical"}}/><a href={prompt.trim()?`${appPath("phi/code/builder")}?q=${encodeURIComponent(prompt.trim())}`:"#"} aria-disabled={!prompt.trim()} style={{...button,display:"block",textAlign:"center",textDecoration:"none",marginTop:10,opacity:prompt.trim()?1:.45}}>Open GPT builder</a></section></div></section></main>
}