"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Check,ChevronLeft,Download,Eye,LayoutTemplate,Palette,Save,Share2,Sparkles,Wand2} from "lucide-react";

type Handoff={token?:{id?:string;query?:string;stage?:string};paper?:{title?:string;dek?:string;overview?:string;engineering?:string[];opportunities?:string[];sources?:{title:string;url:string}[]}};
const HANDOFF="c13b0_infinity_spark_handoff_v3",DRAFTS="c13b0_infinity_studio_drafts_v1";
const palettes=[
 {name:"Deep Current",bg:"#071f38",surface:"#0e3a60",accent:"#8fd3ff",ink:"#ffffff"},
 {name:"Atomic Light",bg:"#f4f8fb",surface:"#ffffff",accent:"#145f94",ink:"#102b40"},
 {name:"Field Lab",bg:"#081e22",surface:"#123b3e",accent:"#d1b65c",ink:"#f8fbf5"},
 {name:"Signal Black",bg:"#090b10",surface:"#181e29",accent:"#b8d8ff",ink:"#ffffff"},
];
export default function InfinityStudio(){
 const[handoff,setHandoff]=useState<Handoff>({}),[stage,setStage]=useState("webpage"),[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[audience,setAudience]=useState("Engineers, researchers, builders, and curious learners"),[goal,setGoal]=useState("Turn the research into a useful, searchable working resource"),[palette,setPalette]=useState(0),[layout,setLayout]=useState("Editorial workspace"),[saved,setSaved]=useState(false),[shared,setShared]=useState(false),[projectId,setProjectId]=useState("");
 useEffect(()=>{try{const encoded=location.hash.startsWith("#project=")?location.hash.slice(9):"",sharedProject=encoded?JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(encoded),x=>x.charCodeAt(0)))):null,h=JSON.parse(localStorage.getItem(HANDOFF)||"{}") as Handoff;setHandoff(h);const params=new URLSearchParams(location.search),nextStage=sharedProject?.stage||params.get("stage")||h.token?.stage||"webpage",query=sharedProject?.title||params.get("query")||h.paper?.title||h.token?.query||"Untitled project";setStage(nextStage);setTitle(query);setProjectId(sharedProject?.id||h.token?.id||crypto.randomUUID());setSummary(sharedProject?.summary||h.paper?.dek||h.paper?.overview?.slice(0,320)||"A focused Infinity project built from a researched query.");if(sharedProject){setAudience(sharedProject.audience);setGoal(sharedProject.goal);setLayout(sharedProject.layout);setPalette(Math.max(0,palettes.findIndex(x=>x.name===sharedProject.palette?.name)))}}catch{}},[]);
 const ideas=useMemo(()=>handoff.paper?.engineering?.length?handoff.paper.engineering:handoff.paper?.opportunities||["Define the central question and measurable outcome.","Choose the clearest working format.","Publish a first useful version and improve it from evidence."],[handoff]);
 function payload(){return{schema:"infinity/studio-project/v1",id:projectId||handoff.token?.id||crypto.randomUUID(),stage,title,summary,audience,goal,palette:palettes[palette],layout,research:handoff.paper||null,status:"DRAFT",updatedAt:new Date().toISOString()}}
 function save(){const draft=payload();try{const all=JSON.parse(localStorage.getItem(DRAFTS)||"[]");localStorage.setItem(DRAFTS,JSON.stringify([draft,...all.filter((x:{id?:string})=>x.id!==draft.id)].slice(0,100)));setSaved(true);setTimeout(()=>setSaved(false),1800)}catch{}}
 function download(){const data=payload(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`${title.toLowerCase().replace(/[^a-z0-9]+/g,"-")||"infinity-project"}-${stage}.json`;a.click();URL.revokeObjectURL(url)}
 async function shareView(){const data=JSON.stringify(payload()),encoded=btoa(Array.from(new TextEncoder().encode(data),x=>String.fromCharCode(x)).join("")),url=`${location.origin}${location.pathname}#project=${encoded}`;try{await navigator.clipboard.writeText(url);setShared(true);setTimeout(()=>setShared(false),1800)}catch{}}
 function buildPage(){save();location.href=`build/?id=${encodeURIComponent(payload().id)}&query=${encodeURIComponent(title)}`}
 const color=palettes[palette];
 return <main className="min-h-screen bg-[#061a30] text-white"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/10 bg-[#061a30]/90 px-4 backdrop-blur-xl sm:px-7"><Link href="/spark/" className="flex items-center gap-2 text-white/75 hover:text-white"><ChevronLeft/>Infinity</Link><div className="font-serif text-xl font-black"><span className="mr-2 font-sans font-light">φ</span>Studio</div><button onClick={save} className="flex items-center gap-2 rounded-full bg-white px-4 py-2 font-bold text-[#0b3154]">{saved?<Check size={17}/>:<Save size={17}/>} {saved?"Saved":"Save"}</button></header>
 <div className="mx-auto grid max-w-7xl gap-6 px-4 py-7 lg:grid-cols-[360px_1fr]">
  <aside className="space-y-5 rounded-[1.7rem] border border-white/10 bg-white/[.06] p-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8fc6ec]">Assembly stage</p><h1 className="mt-2 font-serif text-3xl font-black capitalize">{stage}</h1><p className="mt-2 text-sm leading-6 text-white/60">Research, sources, and the originating token are already attached.</p></div>
   <Field label="Project title"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Purpose"><textarea value={summary} onChange={e=>setSummary(e.target.value)}/></Field><Field label="Intended audience"><input value={audience} onChange={e=>setAudience(e.target.value)}/></Field><Field label="Successful outcome"><textarea value={goal} onChange={e=>setGoal(e.target.value)}/></Field>
   <Field label="Page structure"><select value={layout} onChange={e=>setLayout(e.target.value)}><option>Editorial workspace</option><option>Technical dashboard</option><option>Visual field guide</option><option>Product laboratory</option><option>Research notebook</option></select></Field>
   <div><div className="flex items-center gap-2 font-bold"><Palette size={17}/>Atmosphere</div><div className="mt-3 grid grid-cols-2 gap-2">{palettes.map((p,i)=><button key={p.name} onClick={()=>setPalette(i)} className={`rounded-xl border p-3 text-left text-sm ${palette===i?"border-white":"border-white/10"}`}><span className="mb-2 block h-7 rounded-lg" style={{background:`linear-gradient(110deg,${p.bg},${p.surface},${p.accent})`}}/><b>{p.name}</b></button>)}</div></div>
   <button onClick={buildPage} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#8fd3ff] py-3 font-bold text-[#0b3154]"><Wand2 size={17}/>Open visual page builder</button>
   <div className="grid grid-cols-2 gap-2"><button onClick={shareView} className="flex items-center justify-center gap-2 rounded-xl border border-white/20 py-3 font-bold"><Share2 size={17}/>{shared?"Link copied":"Share view"}</button><button onClick={download} className="flex items-center justify-center gap-2 rounded-xl border border-white/20 py-3 font-bold"><Download size={17}/>Export</button></div>
  </aside>
  <section className="overflow-hidden rounded-[1.7rem] border border-white/10 bg-[#eef3f7] p-3 shadow-2xl"><div className="mb-3 flex items-center justify-between px-2 text-sm font-bold text-[#4b6377]"><span className="flex items-center gap-2"><Eye size={17}/>Live project view</span><span className="capitalize">{stage}</span></div><article className="min-h-[720px] rounded-[1.35rem] p-7 sm:p-12" style={{background:color.bg,color:color.ink}}><nav className="flex items-center justify-between border-b pb-5" style={{borderColor:`${color.ink}22`}}><b className="font-serif text-xl"><span className="mr-2 font-sans font-light">φ</span>{title||"Infinity project"}</b><span className="rounded-full px-3 py-1 text-xs font-bold" style={{background:color.accent,color:color.bg}}>{stage}</span></nav><div className="mx-auto max-w-3xl py-14"><p className="text-sm font-bold uppercase tracking-[.2em]" style={{color:color.accent}}>Curated from research</p><h2 className="mt-4 font-serif text-4xl font-black leading-tight sm:text-6xl">{title||"Your project"}</h2><p className="mt-6 text-xl leading-8 opacity-75">{summary}</p><section className="mt-12 rounded-3xl p-6 sm:p-8" style={{background:color.surface}}><div className="flex items-center gap-2 font-bold" style={{color:color.accent}}><Sparkles size={18}/>Working directions</div><div className="mt-5 grid gap-4">{ideas.slice(0,4).map((idea,i)=><div key={i} className="grid grid-cols-[28px_1fr] gap-3 leading-7"><b style={{color:color.accent}}>{String(i+1).padStart(2,"0")}</b><p>{idea}</p></div>)}</div></section><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border p-5" style={{borderColor:`${color.ink}28`}}><LayoutTemplate style={{color:color.accent}}/><b className="mt-3 block">{layout}</b><p className="mt-2 text-sm opacity-65">{audience}</p></div><div className="rounded-2xl border p-5" style={{borderColor:`${color.ink}28`}}><Sparkles style={{color:color.accent}}/><b className="mt-3 block">Success target</b><p className="mt-2 text-sm opacity-65">{goal}</p></div></div></div></article></section>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-bold">{label}<span className="[&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-white/15 [&>input]:bg-black/20 [&>input]:px-4 [&>input]:py-3 [&>textarea]:min-h-24 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-white/15 [&>textarea]:bg-black/20 [&>textarea]:px-4 [&>textarea]:py-3 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-white/15 [&>select]:bg-[#0b2945] [&>select]:px-4 [&>select]:py-3">{children}</span></label>}
