import type { Metadata, Viewport } from "next";
import "./globals.css";
import "./phi-research.css";
import "./phi-refinement.css";
import "./phi-page2-layout.css";
import "./phi-front-center.css";
import "./open-source-credits.css";
import SiteChrome from "@/components/SiteChrome";
import AppRuntime from "@/components/AppRuntime";
import OpenSourceBuildCredits from "@/components/OpenSourceBuildCredits";
import { appPath } from "@/lib/base-path";
const siteUrl="https://www-infinity4.github.io/C13b0/",phiPreview=`${siteUrl}infinity-phi-share.png?v=20260915-phi-share-2`;
export const metadata:Metadata={metadataBase:new URL(siteUrl),title:"Infinity Phi Search — C13b0",applicationName:"Infinity Phi Search",description:"Infinity Phi Search — indexing, extraction, higher-context decisions and transfer into your world.",alternates:{canonical:siteUrl},openGraph:{type:"website",url:siteUrl,siteName:"Infinity Phi Search",title:"Infinity Phi Search — C13b0",description:"All knowledge. All perspectives. One search. A deeper internet, a clearer tomorrow.",images:[{url:phiPreview,width:1536,height:1024,alt:"Infinity Phi Search C13b0 — indexing, extraction, decision and transfer"}]},twitter:{card:"summary_large_image",title:"Infinity Phi Search — C13b0",description:"All knowledge. All perspectives. One search. A deeper internet, a clearer tomorrow.",images:[phiPreview]}};
export const viewport:Viewport={themeColor:"#071f38",viewportFit:"cover"};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="en" className="scroll-smooth"><head><script defer src="https://unified-wallet.marvaseater.workers.dev/unified-wallet.js"/><style dangerouslySetInnerHTML={{__html:`#testSaleButton,#test-sale-button,[data-action="test-sale"],[data-wallet-action="test-sale"],#shopButton,#shop-button,[data-action="shop"],[data-wallet-action="shop"],#receiptButton,#receipt-button,[data-action="receipt"],[data-wallet-action="receipt"]{display:none!important}body{background:#f8fafd!important}.phi-front-center{width:min(760px,calc(100% - 28px));margin:clamp(44px,8vh,70px) auto 0;text-align:center;position:relative;z-index:25}.phi-front-brand{font:900 1.15rem Georgia,serif;color:#132033;margin-bottom:14px}.phi-front-intent-button{min-height:46px;border:0;border-radius:999px;font:900 .9rem Arial,sans-serif;padding:0 14px;margin:0 3px}.phi-front-intent-images{background:#ffe64f;color:#1d1a00}.phi-front-intent-code{background:#16904d;color:#fff}.phi-front-intent-create{background:#2879d7;color:#fff}.phi-front-search-card{display:flex;align-items:center;gap:9px;min-height:76px;padding:9px;border:3px solid #ff756e;border-radius:24px;background:linear-gradient(145deg,#ea3732,#c91f25)}.phi-front-search-card textarea{flex:1;border:0;outline:0;background:transparent;color:#ffdc57;font:750 1.05rem Arial,sans-serif}.phi-front-search-card textarea::placeholder{color:rgba(255,226,112,.76)}.phi-front-menu-button{display:grid;place-items:center;width:50px;height:50px;border:0;border-radius:16px;background:#168b4c;color:white}.phi-family-links{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:12px}.phi-family-links a{padding:10px 14px;border:1px solid #d9cceb;border-radius:999px;background:#f2eafb;color:#4b2878;text-decoration:none;font:800 .82rem Arial,sans-serif}.phi-home-infinity-counter{position:relative;z-index:30;display:inline-flex;margin:18px 0 0 20px;padding:12px 18px;border:1px solid #d7c7e7;border-radius:999px;background:#efe6f8;color:#512978;text-decoration:none;font:900 .88rem Arial,sans-serif}`}}/><script defer src={appPath("cloud-wallet-client.js?v=20261005-legacy-floor2")}/><script defer src={appPath("infinity-web-startup.js?v=20261003-direct1")}/></head><body className="min-h-screen antialiased" style={{background:"#f8fafd"}}><script defer src={appPath("unified-token-count.js?v=20261004-history2")}/><script defer src={appPath("infinity-starcoin-contract.js?v=20261004-history2")}/><script defer src={appPath("infinity-star-repair.js?v=20261002-starrepair2")}/><AppRuntime/><SiteChrome>{children}</SiteChrome><OpenSourceBuildCredits className="open-source-global-footer" showChatGPT={false}/></body></html>}
