"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Download, ExternalLink, RefreshCw, Save, Sparkles } from "lucide-react";
import { appPath } from "@/lib/base-path";
import { secureLoadDurable, secureSaveDurable } from "@/lib/secure-storage";
import { connectOrCreateWallet } from "@/lib/wallet";
import styles from "./PhiCodeBuilder.module.css";

type Project={id:string;prompt:string;iterations:string[];html:string;created:number;updated:number};
type LedgerItem={id:string;kind:string;color:string;title:string;query:string;status:string;value:number;walletId?:string;createdAt:string};
const PROJECTS="infinity_code_projects_v1";
const LEDGER="c13b0_infinity_token_ledger_v3";
const esc=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]||char));
const clean=(value:unknown)=>String(value||"").replace(/\s+/g," ").trim();

function appKind(prompt:string){
  const p=prompt.toLowerCase();
  if(/bitcoin|crusher|clicker|game|score|level/.test(p))return"game";
  if(/store|shop|marketplace|ebay|listing|catalog/.test(p))return"market";
  if(/search|finder|lookup|index/.test(p))return"search";
  if(/calculator|calculate|math|convert/.test(p))return"calculator";
  if(/quiz|questions|trivia|test/.test(p))return"quiz";
  if(/dashboard|tracker|analytics|status/.test(p))return"dashboard";
  return"app";
}
function titleFrom(prompt:string){const words=clean(prompt).replace(/^(build|make|create|code|an?|the)\s+/i,"").split(" ").slice(0,7).join(" ");return words?words.replace(/\b\w/g,(c)=>c.toUpperCase()):"Infinity App";}
function palette(prompt:string){const p=prompt.toLowerCase();if(/purple/.test(p))return["#6f35a5","#f5effb"];if(/blue/.test(p))return["#1769aa","#eef7ff"];if(/red/.test(p))return["#bb2f2f","#fff2f2"];if(/orange/.test(p))return["#c85a13","#fff5eb"];return["#168b4c","#f2faf5"];}
function features(prompt:string){const p=prompt.toLowerCase();return{dark:/dark|night/.test(p),search:/search|filter|find/.test(p),form:/form|input|submit|add/.test(p),counter:/counter|score|points|click|crusher/.test(p),cards:/cards|tiles|listings|catalog|products/.test(p),timer:/timer|countdown/.test(p)};}

function generatedHtml(prompt:string){
  const kind=appKind(prompt);const title=titleFrom(prompt);const [accent,soft]=palette(prompt);const f=features(prompt);const bg=f.dark?"#071521":"#f5f7fa";const panel=f.dark?"#102536":"#ffffff";const text=f.dark?"#eff7ff":"#172431";const sub=f.dark?"#a9bfd0":"#657282";
  const base=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;background:${bg};color:${text};font-family:Arial,sans-serif}.app{max-width:980px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:24px}.brand{font-weight:900;letter-spacing:.08em}.badge{padding:8px 11px;border-radius:999px;background:${soft};color:${accent};font-size:12px;font-weight:900}.hero{padding:28px;border-radius:28px;background:${panel};box-shadow:0 15px 38px rgba(0,0,0,.08)}h1{margin:0 0 10px;font-size:clamp(34px,7vw,72px);line-height:.95;letter-spacing:-.05em}p{color:${sub};line-height:1.6}.action{border:0;border-radius:14px;background:${accent};color:#fff;padding:13px 17px;font-weight:900;cursor:pointer}.ghost{border:1px solid #ccd5dd;background:transparent;color:${text};padding:12px 15px;border-radius:13px;font-weight:800;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px}.card{padding:18px;border-radius:18px;background:${panel};border:1px solid ${f.dark?"#264357":"#e2e7ec"}}input,select,textarea{width:100%;padding:13px 14px;border:1px solid #ccd5dd;border-radius:13px;background:${panel};color:${text};font:inherit}.row{display:flex;gap:9px;align-items:center}.metric{font-size:42px;font-weight:950;color:${accent}}@media(max-width:680px){.app{padding:15px}.grid{grid-template-columns:1fr}.top{align-items:flex-start}.hero{padding:22px}}</style></head><body><main class="app"><div class="top"><div class="brand">INFINITY APP</div><div class="badge">LIVE PREVIEW</div></div>`;
  let body="";
  if(kind==="game") body=`<section class="hero"><div class="badge">INTERACTIVE GAME</div><h1>${esc(title)}</h1><p>Tap the crusher to earn points. This preview proves the generated page has working state and interaction rather than being a static article.</p><div class="metric" id="score">0</div><div class="row"><button class="action" onclick="score+=10;document.getElementById('score').textContent=score">Crush +10</button><button class="ghost" onclick="score=0;document.getElementById('score').textContent=0">Reset</button></div></section><div class="grid"><div class="card"><b>Level 1</b><p>Reach 100 points.</p></div><div class="card"><b>Multiplier</b><p>Iterations can add upgrades, timers, rewards, media, and wallet hooks.</p></div><div class="card"><b>Status</b><p id="status">Ready to play.</p></div></div><script>let score=0;</script>`;
  else if(kind==="market") body=`<section class="hero"><div class="badge">MARKETPLACE</div><h1>${esc(title)}</h1><p>A working catalog with filtering and interactive listings.</p><input id="find" placeholder="Search listings" oninput="filterItems(this.value)"></section><div class="grid" id="items"><div class="card" data-name="featured item"><b>Featured item</b><p>$24.00 · available now</p><button class="action" onclick="this.textContent='Added'">Add</button></div><div class="card" data-name="second listing"><b>Second listing</b><p>$59.00 · one available</p><button class="action" onclick="this.textContent='Added'">Add</button></div><div class="card" data-name="new listing"><b>New listing</b><p>$12.00 · ready</p><button class="action" onclick="this.textContent='Added'">Add</button></div></div><script>function filterItems(q){document.querySelectorAll('#items .card').forEach(x=>x.style.display=x.dataset.name.includes(q.toLowerCase())?'':'none')}</script>`;
  else if(kind==="search") body=`<section class="hero"><div class="badge">SEARCH APPLICATION</div><h1>${esc(title)}</h1><p>Type into the index and the live result set updates immediately.</p><input id="q" autofocus placeholder="Search this app" oninput="go(this.value)"></section><div class="grid" id="results"><div class="card" data-text="research science engineering"><b>Research</b><p>Science and engineering records.</p></div><div class="card" data-text="business invoice market"><b>Business</b><p>Invoice and market tools.</p></div><div class="card" data-text="media games entertainment"><b>Interactive</b><p>Games, media, and apps.</p></div></div><script>function go(q){q=q.toLowerCase();document.querySelectorAll('#results .card').forEach(x=>x.style.display=x.dataset.text.includes(q)?'':'none')}</script>`;
  else if(kind==="calculator") body=`<section class="hero"><div class="badge">CALCULATOR</div><h1>${esc(title)}</h1><p>Enter two values and calculate instantly.</p><div class="grid"><input id="a" type="number" value="10"><select id="op"><option>+</option><option>-</option><option>×</option><option>÷</option></select><input id="b" type="number" value="5"></div><p class="metric" id="out">15</p><button class="action" onclick="calc()">Calculate</button></section><script>function calc(){let a=+document.getElementById('a').value,b=+document.getElementById('b').value,o=document.getElementById('op').value,r=o==='+'?a+b:o==='-'?a-b:o==='×'?a*b:b?a/b:0;document.getElementById('out').textContent=r}</script>`;
  else if(kind==="quiz") body=`<section class="hero"><div class="badge">QUIZ</div><h1>${esc(title)}</h1><p id="question">Which option should the user choose?</p><div class="grid"><button class="ghost" onclick="answer(this)">Option A</button><button class="ghost" onclick="answer(this)">Option B</button><button class="ghost" onclick="answer(this)">Option C</button></div><p id="answer"></p></section><script>function answer(x){document.getElementById('answer').textContent='Selected: '+x.textContent}</script>`;
  else body=`<section class="hero"><div class="badge">INTERACTIVE APPLICATION</div><h1>${esc(title)}</h1><p>${esc(prompt)}</p><div class="row"><button class="action" onclick="document.getElementById('state').textContent='Action completed at '+new Date().toLocaleTimeString()">Run action</button><button class="ghost" onclick="document.getElementById('state').textContent='Ready'">Reset</button></div><p id="state"><b>Ready</b></p></section><div class="grid"><div class="card"><b>Input</b><p>Describe the next behavior in the iteration box.</p></div><div class="card"><b>State</b><p>Buttons and state are already live.</p></div><div class="card"><b>Responsive</b><p>The preview adapts to phone and desktop widths.</p></div></div>`;
  return `${base}${body}</main></body></html>`;
}

export default function PhiCodeBuilder(){
  const [prompt,setPrompt]=useState("");const [iteration,setIteration]=useState("");const [iterations,setIterations]=useState<string[]>([]);const [steps,setSteps]=useState<string[]>([]);const [building,setBuilding]=useState(true);const [saved,setSaved]=useState("");
  useEffect(()=>{const q=new URLSearchParams(location.search).get("q")||"Interactive Infinity app";setPrompt(q);setSteps(["Reading product intent…"]);const timers=[350,720,1080,1420].map((ms,index)=>window.setTimeout(()=>setSteps((s)=>[...s,["Designing the interaction model…","Composing the responsive interface…","Binding state, controls, and live behavior…","Preview ready for iteration."][index]]),ms));const done=window.setTimeout(()=>setBuilding(false),1480);return()=>{timers.forEach(clearTimeout);clearTimeout(done)}} ,[]);
  const combined=useMemo(()=>[prompt,...iterations].join(" "),[prompt,iterations]);const html=useMemo(()=>generatedHtml(combined),[combined]);
  function iterate(event:FormEvent){event.preventDefault();const next=clean(iteration);if(!next)return;setBuilding(true);setSteps((s)=>[...s,`Iteration ${iterations.length+1}: ${next}`,"Re-evaluating interaction and layout…"]);setIterations((all)=>[...all,next]);setIteration("");window.setTimeout(()=>{setSteps((s)=>[...s,"Preview updated."]);setBuilding(false)},650)}
  async function saveProject(){const project:Project={id:`code-${Date.now()}`,prompt,iterations,html,created:Date.now(),updated:Date.now()};const existing=await secureLoadDurable<Project[]>(PROJECTS,[]).catch(()=>[]);await secureSaveDurable(PROJECTS,[project,...existing].slice(0,50));try{const wallet=connectOrCreateWallet("Infinity Code");const ledger=await secureLoadDurable<LedgerItem[]>(LEDGER,[]).catch(()=>[]);const token:LedgerItem={id:project.id,kind:"code",color:"green",title:titleFrom(combined),query:prompt,status:"finished",value:1,walletId:wallet.walletId,createdAt:new Date().toISOString()};await secureSaveDurable(LEDGER,[token,...ledger.filter((item)=>item.id!==token.id)].slice(0,200));window.dispatchEvent(new Event("infinity-history-updated"));}catch{}setSaved("Saved to this Infinity workspace and indexed in its local project history.")}
  function exportHtml(){const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${titleFrom(combined).replace(/[^a-z0-9]+/gi,"-").toLowerCase()||"infinity-app"}.html`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function openPreview(){const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),10000)}
  return <main className={styles.page}><header className={styles.top}><a href={appPath("phi")}><ArrowLeft size={18}/> Infinity</a><div><b>Code</b><small>Green intent · interactive software</small></div><span className={styles.live}>{building?"BUILDING":"LIVE"}</span></header><section className={styles.workspace}><aside className={styles.console}><div className={styles.consoleHead}><Sparkles size={17}/><div><b>Iteration machine</b><small>The build is visible. The source stays out of the way.</small></div></div><div className={styles.prompt}><small>PRODUCT INTENT</small><p>{prompt}</p></div><div className={styles.steps}>{steps.map((step,index)=><div key={`${step}-${index}`} className={styles.step}><span>{index===steps.length-1&&building?<RefreshCw size={14} className={styles.spin}/>:<Check size={14}/>}</span><p>{step}</p></div>)}</div><form onSubmit={iterate} className={styles.iterate}><label htmlFor="iteration">Tell Infinity what to change next</label><textarea id="iteration" value={iteration} onChange={(e)=>setIteration(e.target.value)} placeholder="Make the score bigger, add a store, put search at the top, change it to dark mode…"/><button disabled={building}>Update preview</button></form><div className={styles.actions}><button onClick={()=>void saveProject()}><Save size={16}/> Save to Infinity</button><button onClick={exportHtml}><Download size={16}/> Export app</button><button onClick={openPreview}><ExternalLink size={16}/> Open</button></div>{saved&&<p className={styles.saved}>{saved}</p>}</aside><section className={styles.preview}><div className={styles.previewTop}><b>Live application preview</b><span>{titleFrom(combined)}</span></div><iframe title="Generated Infinity application" srcDoc={html} sandbox="allow-scripts allow-forms"/></section></section></main>
}
