"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowLeft, Download, ExternalLink, RefreshCw, Save, Sparkles } from "lucide-react";
import { appPath } from "@/lib/base-path";
import { capabilitiesFor, type InfinityIntent } from "@/lib/coder-capabilities";
import { buildWithPhiCodeAgent, importedPhiSkills, loadPhiCodeToolInstructions, type PhiCodeToolSnapshot } from "@/lib/phi-code-agent";

const PROJECT_KEY="infinity_code_projects_v3";
const clean=(value:unknown,max=1800)=>String(value||"").replace(/\s+/g," ").trim().slice(0,max);
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char))}
function fallbackArtifact(prompt:string,message=""){const title=escapeHtml(clean(prompt,500)||"Your generated index will appear here");const note=escapeHtml(clean(message,600));return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;background:#fff;color:#17202a;font-family:system-ui}.shell{padding:28px}.tag{color:#6f2dbd;font-weight:900}h1{font-size:clamp(28px,7vw,54px)}.card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#f7f8fa}.note{color:#8b5d00}</style></head><body><main class="shell"><div class="tag">INDEX PREVIEW</div><h1>${title}</h1><div class="card"><b>Previewer</b><p>Code Phi will render the generated index.html in this window after you press Build.</p>${note?`<p class="note">${note}</p>`:""}</div></main></body></html>`}

export default function PhiCodeBuilderStable({intentOverride}:{intentOverride?:InfinityIntent}={}){
 const [intent]=useState<InfinityIntent>(()=>intentOverride||(typeof window!=="undefined"&&new URLSearchParams(location.search).get("intent")==="create"?"create":"code"));
 const importedSkills=importedPhiSkills(intent),[prompt,setPrompt]=useState(""),[revision,setRevision]=useState(""),[revisions,setRevisions]=useState<string[]>([]),[html,setHtml]=useState(""),[snapshots,setSnapshots]=useState<PhiCodeToolSnapshot[]>([]),[plannedTools,setPlannedTools]=useState<string[]>([]),[building,setBuilding]=useState(false),[status,setStatus]=useState("Ready. Nothing runs until you press Build."),[summary,setSummary]=useState(""),[saved,setSaved]=useState(""),[previewRevision,setPreviewRevision]=useState(0);const buildSerial=useRef(0);
 useEffect(()=>{const initial=clean(new URLSearchParams(location.search).get("q")||"",1800);if(initial){setPrompt(initial);setPlannedTools(capabilitiesFor(initial,intent).slice(0,8).map(cap=>cap.name));setStatus("Request loaded. Review it, then press Build to generate and preview index.html.")}},[intent]);
 async function runBuild(basePrompt:string,nextRevisions:string[],existingHtml:string){const request=clean(basePrompt,1800);if(!request||building)return;const serial=++buildSerial.current,runId=`${intent}-${Date.now().toString(36)}`,fullRequest=[request,...nextRevisions].join("\n");setPlannedTools(capabilitiesFor(fullRequest,intent).slice(0,8).map(cap=>cap.name));setBuilding(true);setSaved("");setSummary("");setStatus("Building index.html…");let toolSnapshots:PhiCodeToolSnapshot[]=[];try{const timeout=new Promise<PhiCodeToolSnapshot[]>(resolve=>setTimeout(()=>resolve([]),2500));toolSnapshots=await Promise.race([loadPhiCodeToolInstructions(fullRequest,runId,intent),timeout]);if(serial!==buildSerial.current)return;setSnapshots(toolSnapshots)}catch{setSnapshots([])}try{const timeout=new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error("Build timed out. The previewer stayed responsive.")),20000));const result=await Promise.race([buildWithPhiCodeAgent({prompt:request,revisions:nextRevisions,currentHtml:existingHtml,runId,snapshots:toolSnapshots,intent}),timeout]);if(serial!==buildSerial.current)return;setHtml(result.html);setSummary(result.summary);setPreviewRevision(v=>v+1);setStatus("index.html generated — preview is live on this page.")}catch(error){if(serial!==buildSerial.current)return;const message=error instanceof Error?error.message:"Build stopped.";setHtml(existingHtml||fallbackArtifact(request,message));setSummary(message);setPreviewRevision(v=>v+1);setStatus("Build stopped safely; the page is still usable.")}finally{if(serial===buildSerial.current)setBuilding(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(building)return;const request=clean(prompt,1800);if(!request)return;setPrompt(request);setRevisions([]);await runBuild(request,[],"")}
 async function iterate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(building)return;const next=clean(revision,1800);if(!next)return;const nextRevisions=[...revisions,next];setRevisions(nextRevisions);setRevision("");await runBuild(prompt,nextRevisions,html)}
 function retry(){if(!building&&prompt.trim())void runBuild(prompt,revisions,html)}
 function save(){if(!html)return;try{const prior=JSON.parse(localStorage.getItem(PROJECT_KEY)||"[]"),list=Array.isArray(prior)?prior:[];localStorage.setItem(PROJECT_KEY,JSON.stringify([{prompt,revisions,html,updatedAt:Date.now(),intent},...list].slice(0,24)));setSaved("Saved on this device.")}catch{setSaved("Could not save locally.")}}
 function download(){if(!html)return;const u=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download="index.html";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
 function openPreview(){if(!html)return;const u=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));window.open(u,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(u),2000)}
 const panel:React.CSSProperties={background:"#fff",border:"1px solid #dfe4ea",borderRadius:18,padding:18,minWidth:0},input:React.CSSProperties={width:"100%",border:"1px solid #cbd3dc",borderRadius:14,background:"#fff",color:"#17202a",padding:13,font:"inherit"},button:React.CSSProperties={border:0,borderRadius:12,background:"#168a52",color:"#fff",padding:"11px 14px",fontWeight:900,cursor:"pointer"},armName=intent==="create"?"Create Phi":"Code Phi";
 return <main style={{minHeight:"100dvh",background:"#f7f8fa",color:"#17202a",fontFamily:"system-ui,sans-serif"}}><header style={{padding:"14px 18px",borderBottom:"1px solid #e1e5e9",background:"#fff"}}><a href={appPath("phi/code")} style={{color:"#17202a",textDecoration:"none",display:"flex",gap:8,alignItems:"center"}}><ArrowLeft size={18}/><b>{armName}</b></a></header><section style={{width:"min(1180px,96vw)",margin:"auto",padding:"20px 0 40px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,360px),1fr))",gap:16}}><section style={panel}><div style={{display:"flex",gap:9,alignItems:"center"}}><Sparkles size={22}/><div><b>Build index.html</b><div style={{fontSize:12,color:"#64707c"}}>Nothing starts automatically.</div></div></div><form onSubmit={submit} style={{display:"grid",gap:10,marginTop:14}}><textarea rows={6} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the page or tool you want generated…" style={{...input,resize:"vertical"}}/><button disabled={building||!prompt.trim()} style={{...button,opacity:building||!prompt.trim()?.55:1}}>{building?"Building…":"Build + Preview"}</button></form><div role="status" style={{marginTop:12,padding:12,borderRadius:12,background:"#f3f5f7"}}>{status}</div>{summary?<p style={{color:"#64707c"}}>{summary}</p>:null}<form onSubmit={iterate} style={{display:"grid",gap:8,marginTop:16}}><textarea rows={3} value={revision} onChange={e=>setRevision(e.target.value)} placeholder="Change the current index…" style={{...input,resize:"vertical"}}/><button disabled={building||!html||!revision.trim()} style={button}>Update Preview</button></form><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:14}}><button type="button" onClick={retry} disabled={building||!prompt.trim()} style={button}><RefreshCw size={14}/> Retry</button><button type="button" onClick={save} disabled={!html} style={button}><Save size={14}/> Save</button><button type="button" onClick={download} disabled={!html} style={button}><Download size={14}/> index.html</button><button type="button" onClick={openPreview} disabled={!html} style={button}><ExternalLink size={14}/> Open</button></div>{saved?<div style={{marginTop:9,color:"#168a52"}}>{saved}</div>:null}</section><section style={{...panel,padding:0,overflow:"hidden",minHeight:"68dvh"}}><div style={{padding:"11px 14px",borderBottom:"1px solid #dfe4ea",display:"flex",justifyContent:"space-between"}}><b>index.html preview</b><span style={{fontSize:12,color:"#64707c"}}>{building?"building":html?"live":"ready"}</span></div><iframe key={`code-preview-${previewRevision}`} title="Generated index preview" sandbox="allow-forms" srcDoc={html||fallbackArtifact(prompt)} style={{width:"100%",minHeight:"64dvh",border:0,background:"white"}}/></section></section></main>
}