"use client";
import { useEffect, useState } from "react";
import { ShoppingCart, X } from "lucide-react";
export const PHI_CART_KEY = "infinity_phi_shop_cart_v1";
export type PhiCartItem = { id:string; title:string; priceLabel:string; imageUrl:string; description:string; collectedAt:string };
let liveCart:PhiCartItem[]=[];
export function readPhiCart():PhiCartItem[]{try{const parsed=JSON.parse(localStorage.getItem(PHI_CART_KEY)||"[]");if(Array.isArray(parsed)){liveCart=parsed.slice(0,100);return liveCart}}catch{}return liveCart}
export function addPhiCartItem(item:Omit<PhiCartItem,"collectedAt">){const current=readPhiCart();const next=[{...item,collectedAt:new Date().toISOString()},...current.filter(x=>x.id!==item.id)].slice(0,100);liveCart=next;try{localStorage.setItem(PHI_CART_KEY,JSON.stringify(next))}catch{}window.dispatchEvent(new CustomEvent("infinity-shop-cart-updated",{detail:{item:next[0],count:next.length,items:next}}));return next}
export default function PhiShopCart(){const[items,setItems]=useState<PhiCartItem[]>([]),[open,setOpen]=useState(false);useEffect(()=>{const refresh=()=>setItems(readPhiCart());refresh();window.addEventListener("storage",refresh);window.addEventListener("infinity-shop-cart-updated",refresh);return()=>{window.removeEventListener("storage",refresh);window.removeEventListener("infinity-shop-cart-updated",refresh)}},[]);function remove(id:string){const next=items.filter(x=>x.id!==id);liveCart=next;try{localStorage.setItem(PHI_CART_KEY,JSON.stringify(next))}catch{}setItems(next);window.dispatchEvent(new CustomEvent("infinity-shop-cart-updated",{detail:{count:next.length,items:next}}))}return <><button type="button" onClick={()=>setOpen(true)} aria-label={`Open Shop cart, ${items.length} items`} className="fixed right-3 top-[74px] z-40 flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 font-black text-slate-900 shadow-xl"><ShoppingCart size={18}/> Shop {items.length?<span className="rounded-full bg-orange-600 px-2 py-0.5 text-xs text-white">{items.length}</span>:null}</button>{open&&<div className="fixed inset-0 z-[70] bg-black/45" onMouseDown={()=>setOpen(false)}><aside className="ml-auto h-full w-full max-w-md overflow-y-auto bg-white p-5 text-slate-950 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Shop cart</h2><button onClick={()=>setOpen(false)} className="grid size-10 place-items-center rounded-full bg-slate-100"><X/></button></div><p className="mt-1 text-sm text-slate-500">Collected advertisements and sale cards.</p><div className="mt-5 space-y-3">{items.length?items.map(item=><article key={item.id} className="flex gap-3 rounded-2xl border p-3"><img src={item.imageUrl} alt="" className="size-20 rounded-xl bg-orange-50 object-contain"/><div className="min-w-0 flex-1"><b>{item.title}</b><p className="text-sm font-black text-orange-700">{item.priceLabel}</p><button onClick={()=>remove(item.id)} className="mt-2 text-xs font-bold text-slate-500 underline">Remove</button></div></article>):<p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">Collect an advertisement and it will appear here.</p>}</div><a href="https://www-infinity4.github.io/Shop-Phi/" className="mt-5 block rounded-full bg-[#3665f3] px-5 py-3 text-center font-black text-white">Open Shop Phi</a></aside></div>}</>}
